### ISSUE TITLE
Provide portData.PortDepartureDelay

### ISSUE THREAD

**Issue by alexmarc-us** [FerryTempo/FTServer#13]
Set the DepartureDelay based on the current time vs the scheduled departure time.
If the vessel in dock, set DepartureDelay as difference between scheduled departure and current time IF >0;
If the vessel not in dock, continue reporting last calculated DepartureDelay.

The FTData object is missing this attribute. See the [FT Server Variables sheet ](https://docs.google.com/spreadsheets/d/1ygASWff6FF5nfwNdA88KGcotJM6jDepFKSyvybwVLmg/edit?usp=share_link) for a description of the expected attributes.

This story will be satisfied once the described attribute exists in the FTData object for any given route.

**Comment by ckulfan** [comment]
using this schema as the source of truth: https://github.com/FerryTempo/FTServer/blob/main/schemas/FerryTempo.schema.json

**Comment by ckulfan** [comment]
Note: port delay and boat delay - need to decide whether or not we reset these data once the boat has left the dock.

**Comment by mattrix14** [comment]
Both persist until new data. This is outlined in the server variables google sheet.BoatDD:- persists until it reaches destination. Then is updated to whatever the computed value is (it may arrive already delayed beyond scheduled sailing).PortDD:- just really BoatDD for the latest departure. Persists until a new boat gets in port.On May 14, 2024, at 18:51, Craig Kulfan ***@***.***> wrote:﻿
Note: port delay and boat delay - need to decide whether or not we reset these data once the boat has left the dock.

**Comment by ckulfan** [comment]
I thought the schema was the source of truth? Should I instead rely on the spreadsheet? If both, how do we keep them in sync?

The code for boat delay today is updated constantly today. I am happy to change it to what is described in the spreadsheet. 
https://github.com/FerryTempo/FTServer/blob/6d7569530b5c42d5af1bec923cbebc58ba1f7ff6/src/FerryTempo.js#L92C1-L92C41

**Comment by mattrix14** [comment]
Good point. I think GitHub should probably be the final word. BUT I need a GitHub lesson to learn how to edit it, haha.Anyway, there shouldn’t be any discrepancies between the two (I think… 😬)On May 14, 2024, at 19:52, Craig Kulfan ***@***.***> wrote:﻿
I thought the schema was the source of truth? Should I instead rely on the spreadsheet? If both, how do we keep them in sync?
The code for boat delay today is updated constantly today. I am happy to change it to what is described in the spreadsheet.
https://github.com/FerryTempo/FTServer/blob/6d7569530b5c42d5af1bec923cbebc58ba1f7ff6/src/FerryTempo.js#L92C1-L92C41
