### ISSUE TITLE
Provide portData.PortDepartureDelayAverage

### ISSUE THREAD

**Issue by alexmarc-us** [FerryTempo/FTServer#14]
The FTData object is missing this attribute. See the [FT Server Variables sheet ](https://docs.google.com/spreadsheets/d/1ygASWff6FF5nfwNdA88KGcotJM6jDepFKSyvybwVLmg/edit?usp=share_link) for a description of the expected attributes.

This story will be satisfied once the described attribute exists in the FTData object for any given route.

**Comment by ckulfan** [comment]
This change has been completed and merged
