### ISSUE TITLE
Unexpected reporting of "boat at dock" status

### ISSUE THREAD

**Issue by alexmarc-us** [FerryTempo/FTServer#27]
See rows 85 - 90

[Defect - Boats arriving.xlsx](https://github.com/FerryTempo/FTServer/files/13791185/Defect.-.Boats.arriving.xlsx)

**Comment by ckulfan** [comment]
Looking at the code, I am a little confused with regard to what the following line of code in FerryTemp.js is doing:
        targetRoute['portData'][departingPort].BoatAtDock = DepartingTerminalAbbrev && AtDock && InService;

AtDock and InService are both boolean values but DepartingTerminalAbbrev is a constant string.

**Comment by alexmarc-us** [comment]
Sorry, this issue should be marked as closed. It moved to Done but the issue remained open. 'Doh!

`targetRoute['portData'][departingPort].BoatAtDock = DepartingTerminalAbbrev && AtDock && InService` casts the value to a boolean. If there is a truthy value for each DepartingTerminalAbbrev && AtDock && InService, it is set to `true`. Otherwise it's false.
