### ISSUE TITLE
Error handling for invalid WSF API key

### ISSUE THREAD

**Issue by jzkaye** [FerryTempo/FTServer#34]
If WSF_API_KEY key is not defined or is invalid, the server code fails in FerryTempo.js with "TypeError: newFerryData is not iterable".

It would be nice to detect that WSF doesn't like the key and log a message to the console.

**Comment by ckulfan** [comment]
I just pushed a branch with changes that test for the API key at start up and error out if it is unset. At the same time, I added a check for the fetch command from WSDOT that looks for a status code of 200 and only processes the request if one is received. This stops the app from crashing on iterable but we may want to modify this in the future.

**Comment by alexmarc-us** [comment]
Thanks so much for the contribution @ckulfan!

If you think the change is ready for review/merge, please take a look at our [Contributing guide](https://github.com/FerryTempo/FTServer/blob/main/docs/Contributing.md) and create a Pull Request. There's a demo of this workflow [available on our Slack](https://ferry-tempo.slack.com/archives/C030S31FYVD/p1704604187377759) as well.

Please let me know if you have any questions, and thanks again.
