### ISSUE TITLE
Provide portData.PortArrivalTimeMinus

### ISSUE THREAD

**Issue by alexmarc-us** [FerryTempo/FTServer#54]
The FTData object is missing this attribute. See the [FT Server Variables sheet ](https://docs.google.com/spreadsheets/d/1ygASWff6FF5nfwNdA88KGcotJM6jDepFKSyvybwVLmg/edit?usp=share_link)for a description of the expected attributes.

This story will be satisfied once the described attribute exists in the FTData object for any given route.

**Comment by ckulfan** [comment]
Looking at the current code, the BoatETA value is returned as epoch seconds, when I think it is supposed to be the difference between the provided ETA and the current time. I am going to fix that while also creating the Port data requested in the issue.

**Comment by ckulfan** [comment]
Pull request created and submitted for review.
