### ISSUE TITLE
Boat two had both dock lights lit at same time

### ISSUE THREAD

**Issue by ckulfan** [FerryTempo/FTServer#83]
The clock had both dock lights lit for boat two and the bainbridge light lit for boat one. Here is a copy of the data packet at that time: (note both boats are reporting as at dock in bainbridge)

sea-bi": {
        "boatData": {
            "boat1": {
                "ArrivalTimeMinus": 0,
                "ArrivingTerminalAbbrev": null,
                "ArrivingTerminalName": null,
                "AtDock": true,
                "BoatDepartureDelay": 0,
                "BoatETA": 0,
                "DepartingTerminalName": "Bainbridge Island",
                "DepartingTerminalAbbrev": "BBI",
                "DepartureDelayAverage": 1796,
                "Direction": "ES",
                "Heading": 280,
                "InService": true,
                "LeftDock": 0,
                "OnDuty": true,
                "PositionUpdated": 1720691985,
                "Progress": 0,
                "ScheduledDeparture": 0,
                "Speed": 0,
                "StopTimer": 2545,
                "VesselName": "Tacoma",
                "VesselPosition": 1
            },
            "boat2": {
                "ArrivalTimeMinus": 0,
                "ArrivingTerminalAbbrev": null,
                "ArrivingTerminalName": null,
                "AtDock": true,
                "BoatDepartureDelay": 0,
                "BoatETA": 0,
                "DepartingTerminalName": "Bainbridge Island",
                "DepartingTerminalAbbrev": "BBI",
                "DepartureDelayAverage": 751,
                "Direction": "ES",
                "Heading": 272,
                "InService": true,
                "LeftDock": 0,
                "OnDuty": true,
                "PositionUpdated": 1720690659,
                "Progress": 0,
                "ScheduledDeparture": 0,
                "Speed": 0,
                "StopTimer": 12321,
                "VesselName": "Sealth",
                "VesselPosition": 2
            }
        },
        "routeID": "5",
        "portData": {
            "portES": {
                "TerminalName": "Seattle",
                "TerminalAbbrev": "P52",
                "TerminalID": 7,
                "BoatAtDock": false,
                "NextScheduledSailing": null,
                "PortDepartureDelay": 670,
                "PortETA": 0,
                "PortArrivalTimeMinus": 0,
                "PortStopTimer": 0,
                "PortDepartureDelayAverage": 1272
            },
            "portWN": {
                "TerminalName": "Bainbridge Island",
                "TerminalAbbrev": "BBI",
                "TerminalID": 3,
                "BoatAtDock": true,
                "NextScheduledSailing": null,
                "PortDepartureDelay": 0,
                "PortETA": 1720689540,
                "PortStopTimer": 12321,
                "PortDepartureDelayAverage": 1588,
                "PortArrivalTimeMinus": 2
            }
        }
    },

**Comment by ckulfan** [comment]
Here is the WSDOT data at the same time:
  },
    {
        "VesselID": 28,
        "VesselName": "Sealth",
        "Mmsi": 366710820,
        "DepartingTerminalID": 3,
        "DepartingTerminalName": "Bainbridge Island",
        "DepartingTerminalAbbrev": "BBI",
        "ArrivingTerminalID": 7,
        "ArrivingTerminalName": "Seattle",
        "ArrivingTerminalAbbrev": "P52",
        "Latitude": 47.601325,
        "Longitude": -122.342137,
        "Speed": 5.2,
        "Heading": 60,
        "InService": true,
        "AtDock": false,
        "LeftDock": "/Date(1720706807000-0700)/",
        "Eta": "/Date(1720708920000-0700)/",
        "EtaBasis": "Vessel Sealth departed Bainbridge going to Colman and using vessel Sealth closest location data from Jul 11 2024  5:54AM",
        "ScheduledDeparture": "/Date(1720706700000-0700)/",
        "OpRouteAbbrev": [],
        "VesselPositionNum": null,
        "SortSeq": 9999,
        "ManagedBy": 1,
        "TimeStamp": "/Date(1720708881000-0700)/",
        "VesselWatchShutID": 23,
        "VesselWatchShutMsg": "VesselWatch data temporarily unavailable. ",
        "VesselWatchShutFlag": "0",
        "VesselWatchStatus": "0",
        "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
    },

    {
        "VesselID": 32,
        "VesselName": "Tacoma",
        "Mmsi": 366772760,
        "DepartingTerminalID": 3,
        "DepartingTerminalName": "Bainbridge Island",
        "DepartingTerminalAbbrev": "BBI",
        "ArrivingTerminalID": null,
        "ArrivingTerminalName": null,
        "ArrivingTerminalAbbrev": null,
        "Latitude": 47.622053,
        "Longitude": -122.509212,
        "Speed": 0.2,
        "Heading": 284,
        "InService": true,
        "AtDock": true,
        "LeftDock": null,
        "Eta": null,
        "EtaBasis": null,
        "ScheduledDeparture": "/Date(1720709700000-0700)/",
        "OpRouteAbbrev": [],
        "VesselPositionNum": null,
        "SortSeq": 9999,
        "ManagedBy": 1,
        "TimeStamp": "/Date(1720708880000-0700)/",
        "VesselWatchShutID": 20,
        "VesselWatchShutMsg": "Vessel information unavailable",
        "VesselWatchShutFlag": "0",
        "VesselWatchStatus": "0",
        "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
    },

**Comment by mattrix14** [comment]
Is this possibly a client issue?On Jul 11, 2024, at 07:49, Craig Kulfan ***@***.***> wrote:﻿
Here is the WSDOT data at the same time:
},
{
"VesselID": 28,
"VesselName": "Sealth",
"Mmsi": 366710820,
"DepartingTerminalID": 3,
"DepartingTerminalName": "Bainbridge Island",
"DepartingTerminalAbbrev": "BBI",
"ArrivingTerminalID": 7,
"ArrivingTerminalName": "Seattle",
"ArrivingTerminalAbbrev": "P52",
"Latitude": 47.601325,
"Longitude": -122.342137,
"Speed": 5.2,
"Heading": 60,
"InService": true,
"AtDock": false,
"LeftDock": "/Date(1720706807000-0700)/",
"Eta": "/Date(1720708920000-0700)/",
"EtaBasis": "Vessel Sealth departed Bainbridge going to Colman and using vessel Sealth closest location data from Jul 11 2024  5:54AM",
"ScheduledDeparture": "/Date(1720706700000-0700)/",
"OpRouteAbbrev": [],
"VesselPositionNum": null,
"SortSeq": 9999,
"ManagedBy": 1,
"TimeStamp": "/Date(1720708881000-0700)/",
"VesselWatchShutID": 23,
"VesselWatchShutMsg": "VesselWatch data temporarily unavailable. ",
"VesselWatchShutFlag": "0",
"VesselWatchStatus": "0",
"VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
},
{
    "VesselID": 32,
    "VesselName": "Tacoma",
    "Mmsi": 366772760,
    "DepartingTerminalID": 3,
    "DepartingTerminalName": "Bainbridge Island",
    "DepartingTerminalAbbrev": "BBI",
    "ArrivingTerminalID": null,
    "ArrivingTerminalName": null,
    "ArrivingTerminalAbbrev": null,
    "Latitude": 47.622053,
    "Longitude": -122.509212,
    "Speed": 0.2,
    "Heading": 284,
    "InService": true,
    "AtDock": true,
    "LeftDock": null,
    "Eta": null,
    "EtaBasis": null,
    "ScheduledDeparture": "/Date(1720709700000-0700)/",
    "OpRouteAbbrev": [],
    "VesselPositionNum": null,
    "SortSeq": 9999,
    "ManagedBy": 1,
    "TimeStamp": "/Date(1720708880000-0700)/",
    "VesselWatchShutID": 20,
    "VesselWatchShutMsg": "Vessel information unavailable",
    "VesselWatchShutFlag": "0",
    "VesselWatchStatus": "0",
    "VesselWatchMsg": "WSF's VesselWatch page is currently not responding and is out of service. Thank you for your patience while we work to restore this page. "
},

**Comment by ckulfan** [comment]
Notice that
OpRouteAbbrev": [], is blank, which effectively breaks our software.

**Comment by ckulfan** [comment]
The fix for this issue is to assert the state for the ES/WN dock light based on the fact that both should never be on at the same time for the same boat.l

   if (jsonDoc["boatData"]["boat1"]["Direction"] == "WN") {
      B1DockLampES.turnOn();
      B1DockLampWN.turnOff();                                                            // Show which dock
      Boat1ProgressDial.targetPosition = B1progress * Boat1ProgressDial.maxSteps;       // Set Boat Progress target position
    }
    else {
      B1DockLampWN.turnOn();
      B1DockLampES.turnOff();
      Boat1ProgressDial.targetPosition = (1 - B1progress) * Boat1ProgressDial.maxSteps; // Set Boat Progress target position
    }

**Comment by klaplain** [comment]
I can do that!

**Comment by ckulfan** [comment]
The fix for this has been committed on branch POS2_LatestLibs
