### ISSUE TITLE
Provide boatData.StopTimer

### ISSUE THREAD

**Issue by alexmarc-us** [FerryTempo/FTServer#9]
The FTData object is missing this attribute. See the [FT Server Variables sheet ](https://docs.google.com/spreadsheets/d/1ygASWff6FF5nfwNdA88KGcotJM6jDepFKSyvybwVLmg/edit?usp=share_link) for a description of the expected attributes.

This story will be satisfied once the described attribute exists in the FTData object for any given route.

**Comment by ckulfan** [comment]
Calculating StopTimer for the boat using the epochTimestamp value when we first see the boat arrive AtDock and the current time. This is reset to zero once the boat leaves the dock.
